import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Ledger } from '../src/lib/ledger';
import type { ChainProof } from '../src/lib/chain-types';
import { requireLocal } from '../src/lib/local-access';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const recipient = '0x' + 'a'.repeat(40), payer = '0x' + 'b'.repeat(40);
function setup() { const db = new Ledger(':memory:'); db.setRecipient(recipient); const row = db.create({customer:'Client',description:'Design',amount:'1.123456',payer},100); return {db,row}; }
function proof(): ChainProof { return { outcome:'verified',summary:'Verified',transactionHash:'0x'+'c'.repeat(64),chainId:10143,tokenAddress:'0x534b2f3A21130d7a60830c2Df862319e593943A3',recipient,expectedAmount:'1.123456',receivedAmount:'1.123456',blockNumber:101,blockHash:'0x'+'d'.repeat(64),finalizedThrough:102,checkedAt:new Date().toISOString(),transfers:[{evidenceId:'10143:tx:0',from:payer,to:recipient,amount:'1.123456',logIndex:0,isMint:false}] }; }
test('records verified payment and prevents evidence reuse across requests', () => { const {db,row} = setup(); db.match(row.id,proof()); assert.equal(db.request(row.id).status,'received'); const second=db.create({customer:'Other',description:'Design',amount:'1.123456',payer},100); assert.throws(()=>db.match(second.id,proof()),/counted twice/); assert.equal(db.request(second.id).status,'awaiting'); db.db.close(); });
test('historical funding cannot pay an invoice or be imported twice',()=>{const {db,row}=setup(); db.importFunding(proof(),'Funding'); assert.throws(()=>db.match(row.id,proof()),/counted twice/); assert.throws(()=>db.importFunding(proof(),'Again'),/counted twice/); assert.equal(db.snapshot().funding.length,1); db.db.close();});
test('rejects pre-request evidence, incorrect sender and mint',()=>{const {db,row}=setup(); assert.throws(()=>db.match(row.id,{...proof(),blockNumber:100}),/predates/); const wrong=proof();wrong.transfers[0].from=recipient;assert.throws(()=>db.match(row.id,wrong),/payer/);const mint=proof();mint.transfers[0].isMint=true;assert.throws(()=>db.match(row.id,mint),/payer/);assert.equal(db.request(row.id).status,'awaiting');db.db.close();});
test('rejects mismatches and nonfinal receipts without claiming evidence',()=>{const {db,row}=setup();assert.throws(()=>db.match(row.id,{...proof(),outcome:'not_finalized'}));assert.throws(()=>db.match(row.id,{...proof(),expectedAmount:'2'}),/match/);db.match(row.id,proof());assert.equal(db.request(row.id).status,'received');db.db.close();});
test('tracking hides names and notes; changing wallet preserves existing request',()=>{const {db,row}=setup();db.note(row.id,'Private customer information');db.setRecipient(payer);const track=db.tracking(row.token)!;assert.equal(track.recipient,recipient);assert.ok(!('customer' in track));assert.ok(!('notes' in track));assert.equal(db.tracking('bad'),null);assert.equal(db.request(row.id).notes.length,1);db.db.close();});
test('database survives closing and reopening',()=>{const dir=mkdtempSync(join(tmpdir(),'paytrace-ledger-'));try { const path=join(dir,'ledger.sqlite'); const first=new Ledger(path);first.setRecipient(recipient);first.importFunding(proof(),'Funding');first.db.close();const second=new Ledger(path);assert.equal(second.snapshot().recipient,recipient);assert.equal(second.snapshot().funding.length,1);assert.throws(()=>second.importFunding(proof(),'Duplicate'),/counted twice/);second.db.close(); }finally{rmSync(dir,{recursive:true,force:true});}});
test('local access blocks remote hosts and cross-site requests',()=>{assert.doesNotThrow(()=>requireLocal(new Request('http://localhost:3100/api/ledger',{headers:{host:'localhost:3100',origin:'http://localhost:3100'}})));assert.throws(()=>requireLocal(new Request('https://evil.example/api/ledger',{headers:{host:'evil.example'}})),/local-only/);assert.throws(()=>requireLocal(new Request('http://localhost:3100/api/ledger',{headers:{host:'localhost:3100',origin:'https://evil.example'}})),/workspace/);});
