'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, CheckCircle2, CircleAlert, Clock3, Copy, Download, Loader2, ShieldCheck, Wallet } from 'lucide-react';
import type { TrackingRecord } from '@/lib/ledger-types';
import { MONAD_TESTNET } from '@/lib/chain-types';
import { tokenAmount } from '@/lib/payments';
import { sendPayment, type WalletProvider } from '@/lib/wallet-payment';
import { downloadFile } from '@/lib/exports';
export function Checkout({initial,token}:{initial:TrackingRecord;token:string}){
  const [row,setRow]=useState(initial),[hash,setHash]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[copied,setCopied]=useState('');
  const checking=useRef(false), attempt=useRef(0);
  const key=`paytrace-submission-${token}`;
  useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved&&/^0x[0-9a-f]{64}$/i.test(saved)&&initial.status==='awaiting'){setHash(saved);setPending(true);}}catch{}},[key,initial.status]);
  async function verify(tx:string){if(checking.current)return;checking.current=true;setBusy(true);setError('');try{const res=await fetch(`/api/track/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transactionHash:tx})});const data=await res.json();if(!res.ok)throw new Error(data.error);if(data.pending){setPending(true);setMessage('Transaction submitted. Waiting for a finalized receipt…');}else{setRow(data);setPending(false);setMessage(data.status==='received'?'Your payment has been verified and saved.':'This request is closed.');try{localStorage.removeItem(key);}catch{}}}catch(e){setPending(false);setError(e instanceof Error?e.message:'We could not check the payment. Retry verification; do not send again.');}finally{checking.current=false;setBusy(false);}}
  useEffect(()=>{if(!pending||!hash||row.status!=='awaiting')return;const timer=setInterval(()=>{attempt.current++;if(attempt.current>=30){setPending(false);setMessage('Still waiting. Your transaction hash is saved; you can check it again below.');return;}void verify(hash);},8000);return()=>clearInterval(timer);},[pending,hash,row.status]); // verification is bounded to four minutes
  useEffect(()=>{if(row.status!=='awaiting')return;const timer=setInterval(async()=>{try{const res=await fetch(`/api/track/${token}`,{cache:'no-store'});if(res.ok){const data=await res.json();setRow(data);if(data.status!=='awaiting')setPending(false);}}catch{}},15000);return()=>clearInterval(timer);},[row.status,token]);
  async function pay(){setBusy(true);setError('');setMessage('Review the recipient and amount in your wallet.');try{const provider=(window as unknown as {ethereum?:WalletProvider}).ethereum;if(!provider)throw new Error('Open this page in a browser with an Ethereum-compatible wallet extension, or use the manual payment details below.');const tx=await sendPayment(provider,row);setHash(tx);try{localStorage.setItem(key,tx);}catch{}attempt.current=0;setPending(true);await verify(tx);}catch(e){const code=(e as {code?:number}).code;setError(code===4001?'You declined the wallet request. No payment was recorded.':e instanceof Error?e.message:'The wallet could not submit the transfer. Check your USDC and MON gas balance.');setMessage('');}finally{setBusy(false);}}
  async function copy(value:string,name:string){try{await navigator.clipboard.writeText(value);setCopied(name);}catch{setError('Select and copy the address below. Clipboard access is unavailable.');}}
  const paid=row.status==='received',closed=row.status==='cancelled';
  return <div className="checkout-shell"><header className="checkout-header"><a className="verify-brand" href="/">paytrace.</a><span><span className="live-dot"/>Monad testnet</span><span className="checkout-secure"><ShieldCheck size={14}/>Onchain verification</span></header><main className="checkout-main"><div className="checkout-intro"><div className="eyebrow">A CLEAR PATH FROM SENT TO RECEIVED</div><h1>{paid?'All accounted for.':closed?'This request is closed.':'Good work deserves\na clear payment.'}</h1><p>{paid?'Your transfer has been checked and recorded. Your receipt is ready.':closed?'The requester cancelled this payment. Do not send funds to this request.':'Pay directly from your wallet. We’ll follow the transfer and confirm when it arrives.'}</p></div><div className="checkout-grid"><section className={`card checkout-card ${paid?'paid':''}`}><div className="checkout-card-head"><span className="checkout-icon">{paid?<CheckCircle2/>:closed?<CircleAlert/>:<Wallet/>}</span><span className={`live-status ${row.status}`}>{paid?'Payment received':closed?'Cancelled':pending?'Confirming transfer':'Payment requested'}</span></div><p className="checkout-description">{row.description}</p><div className="checkout-amount">{tokenAmount(row.amount)}<span>test USDC</span></div><div className="checkout-meta"><span>Request reference</span><code>{row.id.slice(0,15).toUpperCase()}</code><span>Created</span><span>{new Date(row.createdAt).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span></div>
      {paid?<div className="checkout-received"><CheckCircle2 size={22}/><div><strong>Received. Verified. Recorded.</strong><p>Correct sender, recipient and amount. Finalized on Monad.</p></div></div>:!closed&&<><button className="button primary checkout-pay" onClick={()=>void pay()} disabled={busy||pending||Boolean(hash)}>{busy||pending?<Loader2 className="spinning" size={18}/>:<Wallet size={18}/>} {pending?'Confirming onchain…':hash?'Transaction hash saved below':'Pay with your wallet'}</button><p className="checkout-fine">{hash?'Verify the existing transfer below before sending another payment.':'Your wallet asks you to approve the exact transfer. No token allowance required.'}</p></>}
      {message&&<div className="checkout-message" role="status"><Clock3 size={16}/>{message}</div>}{error&&<div className="checkout-error" role="alert"><CircleAlert size={18}/><span>{error}</span></div>}
      {paid&&<div className="checkout-receipt-actions"><button className="button primary" onClick={()=>downloadFile(`${row.id}-receipt.json`,JSON.stringify({request:row.id,description:row.description,amount:row.amount,network:MONAD_TESTNET.name,proof:row.proof},null,2))}><Download size={16}/>Download receipt</button><button className="button secondary" onClick={()=>window.print()}>Print receipt</button></div>}
      <div className="checkout-recipient"><span>Receiving wallet</span><button title="Copy receiving wallet" onClick={()=>void copy(row.recipient,'recipient')}><code>{row.recipient}</code>{copied==='recipient'?<Check size={15}/>:<Copy size={15}/>}</button><span>Expected payer</span><code>{row.payer}</code></div>{paid&&<a className="checkout-explorer" target="_blank" rel="noreferrer" href={`${MONAD_TESTNET.explorer}/tx/${row.transactionHash}`}>View the onchain receipt <ArrowUpRight size={15}/></a>}</section>
      <aside className="checkout-side"><section className="card checkout-journey"><h2>Your payment journey</h2><ol><li className="done"><span><Check size={14}/></span><div><strong>Request created</strong><p>The amount and receiving wallet are locked to this request.</p></div></li><li className={paid?'done':''}><span>{paid?<Check size={14}/>:2}</span><div><strong>{paid?'Transfer submitted':'Send from your wallet'}</strong><p>{paid?'Your transaction is recorded on Monad.':'Use the expected payer account and keep a little test MON for gas.'}</p></div></li><li className={paid?'done':''}><span>{paid?<Check size={14}/>:3}</span><div><strong>{paid?'Verified and received':'We verify the evidence'}</strong><p>We check the token, amount, wallets and finalization. A transfer is counted once.</p></div></li></ol></section>
      {!paid&&!closed&&<section className="card checkout-manual"><h2>Already sent it?</h2><p>Paste the transaction hash from your wallet. We’ll check the transfer without sending funds.</p><form onSubmit={e=>{e.preventDefault();attempt.current=0;try{localStorage.setItem(key,hash);}catch{}void verify(hash);}}><label>Transaction hash<input value={hash} onChange={e=>{setHash(e.target.value);setPending(false);}} required pattern="0x[a-fA-F0-9]{64}" placeholder="0x…" disabled={busy||pending}/></label><button className="button secondary" disabled={busy||pending}>Verify existing transfer</button></form><details><summary>Manual payment details</summary><p>Network: Monad Testnet · chain 10143</p><p>Token contract: <code>{MONAD_TESTNET.usdc}</code></p><p>Use the receiving address and exact amount on this page. Send after the request was created.</p></details></section>}
      <div className="checkout-trust"><ShieldCheck size={21}/><p>Funds travel directly between wallets. PayTrace records the evidence and never holds your keys.</p></div></aside></div><footer className="checkout-footer"><span>Clarity in every transfer.</span><span>Testnet tokens have no monetary value. Onchain receipt is not bank settlement.</span></footer></main></div>;
}
