'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, CircleAlert, Copy, ExternalLink, FileSearch, Loader2, LockKeyhole, Radio, ShieldCheck, Wallet } from 'lucide-react';
import { MONAD_TESTNET, type ChainProof } from '@/lib/chain-types';
import { tokenAmount } from '@/lib/payments';
export function VerifyWorkspace() {
  const [proof, setProof] = useState<ChainProof | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  async function verify(form: HTMLFormElement) {
    const data = new FormData(form); setBusy(true); setError(''); setProof(null); setCopied(false);
    try {
      const response = await fetch('/api/verify', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({transactionHash:data.get('hash'), recipient:data.get('recipient'), expectedAmount:data.get('amount')}), signal:AbortSignal.timeout(45000)});
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || 'Verification could not be completed.');
      setProof(payload);
    } catch(e) { setError(e instanceof Error && e.name !== 'TimeoutError' ? e.message : 'The verification timed out. No payment was changed. Please retry.'); }
    finally { setBusy(false); }
  }
  return <div className="verify-shell"><header className="verify-header"><Link href="/" className="verify-brand">paytrace<span>.</span></Link><span><Radio size={13} />Monad testnet · read-only</span><Link href="/" className="text-button"><ArrowLeft size={14} />Payment workspace</Link></header><main className="verify-main"><div className="eyebrow">REAL EVIDENCE. NO GUESSWORK.</div><h1>Let’s verify that transfer.</h1><p className="verify-intro">Check a real testnet transaction against the recipient and amount you expected. No wallet connection. No signatures. Just the evidence.</p><div className="verify-grid"><section className="card verify-form-card"><div className="card-heading"><div><h2>Transfer details</h2><p>Circle’s test USDC on Monad · chain {MONAD_TESTNET.chainId}</p></div><FileSearch size={21} /></div><form onSubmit={e => {e.preventDefault(); void verify(e.currentTarget);}}><label>Transaction hash<input name="hash" required pattern="0x[a-fA-F0-9]{64}" placeholder="0x… (64 characters after 0x)" autoComplete="off" spellCheck={false} disabled={busy} /></label><label>Expected recipient<input name="recipient" required pattern="0x[a-fA-F0-9]{40}" placeholder="The wallet that should receive the USDC" autoComplete="off" spellCheck={false} disabled={busy} /></label><label>Expected amount<div className="amount-input"><input name="amount" required inputMode="decimal" pattern="[0-9]{1,12}(\.[0-9]{1,6})?" placeholder="e.g. 1.00" disabled={busy} /><span>test USDC</span></div></label><button className="button primary verify-submit" disabled={busy} type="submit">{busy ? <><Loader2 size={17} className="spinning" />Checking the chain…</> : <>Verify transfer <ArrowRight size={16} /></>}</button><p className="verify-form-hint"><LockKeyhole size={13} />Reads public chain data. Does not send funds or change a payment.</p></form></section><aside className="verify-explainer"><span className="verify-emblem"><ShieldCheck size={30} /></span><h2>What we check</h2><ol><li><Check size={15} /><div><strong>The right network</strong><p>The RPC must identify itself as Monad testnet.</p></div></li><li><Check size={15} /><div><strong>A successful, finalized transaction</strong><p>Receipt, canonical block and finalized block evidence must agree.</p></div></li><li><Check size={15} /><div><strong>The actual USDC event</strong><p>We check Circle’s contract, recipient and exact amount—not the token name.</p></div></li></ol><div className="verify-boundary"><CircleAlert size={16} /><p>Test tokens have no monetary value. A matching transfer does not prove invoice ownership, a provider payout, or bank receipt.</p></div><a href="https://www.circle.com/blog/now-available-usdc-cctp-wallets-and-contracts-on-monad" target="_blank" rel="noreferrer">Verify the supported token with Circle <ExternalLink size={12} /></a></aside></div>
      {error && <div className="verify-error" role="alert"><CircleAlert size={20} /><div><strong>We couldn’t verify this transfer.</strong><p>{error}</p></div></div>}
      {proof && <section className={`card proof-card ${proof.outcome === 'verified' ? 'proof-success' : 'proof-review'}`} aria-live="polite"><div className="proof-heading"><span>{proof.outcome === 'verified' ? <CheckCircle2 size={27} /> : <CircleAlert size={27} />}</span><div><div className="eyebrow">MONAD TESTNET EVIDENCE</div><h2>{proof.outcome === 'verified' ? 'Recipient and amount match.' : proof.outcome === 'amount_mismatch' ? 'This transfer needs a closer look.' : proof.outcome === 'reverted' ? 'The transaction reverted.' : proof.outcome === 'not_finalized' ? 'Waiting for finalization.' : proof.outcome === 'no_transfer' ? 'No matching USDC recipient.' : 'No receipt available yet.'}</h2><p>{proof.summary}</p></div></div><div className="proof-amounts"><div><span>Expected</span><strong>{tokenAmount(proof.expectedAmount)} <small>test USDC</small></strong></div><div><span>Observed for recipient</span><strong>{proof.receivedAmount === null ? 'Not established' : tokenAmount(proof.receivedAmount)}{proof.receivedAmount !== null && <small> test USDC</small>}</strong></div><div><span>Provider payout</span><strong className="proof-unknown">Not checked</strong></div></div><dl className="proof-facts"><div><dt>Transaction</dt><dd><a href={`${MONAD_TESTNET.explorer}/tx/${proof.transactionHash}`} target="_blank" rel="noreferrer">{proof.transactionHash}<ExternalLink size={12} /></a></dd></div><div><dt>Recipient</dt><dd>{proof.recipient}</dd></div><div><dt>USDC contract</dt><dd>{proof.tokenAddress}</dd></div><div><dt>Receipt block</dt><dd>{proof.blockNumber?.toLocaleString() ?? 'Not established'}</dd></div><div><dt>Finalized through</dt><dd>{proof.finalizedThrough?.toLocaleString() ?? 'Not established'}</dd></div><div><dt>Checked at</dt><dd>{new Date(proof.checkedAt).toLocaleString()}</dd></div></dl>{proof.transfers.length > 0 && <div className="proof-events"><h3>Observed transfer events</h3>{proof.transfers.map(t => <div key={t.evidenceId}><Wallet size={17} /><span><strong>{tokenAmount(t.amount)} test USDC {t.isMint && <small>· Mint / faucet</small>}</strong><span>From {t.from}</span><code>Event {t.logIndex} · {t.evidenceId}</code></span></div>)}</div>}<div className="proof-footer"><p>No invoice has been assigned and no demo record was modified.</p><button className="button secondary" onClick={async () => { try { await navigator.clipboard.writeText(JSON.stringify(proof, null, 2)); setCopied(true); } catch { setError('Copy is unavailable in this browser. The evidence remains visible above.'); } }}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Evidence copied' : 'Copy evidence'}</button></div></section>}
      <footer className="verify-footer"><span>Every payment, accounted for.</span><span>Verification uses a public RPC response, not an independent consensus client.</span></footer>
    </main></div>;
}
