'use client';

import Link from 'next/link';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDown, ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, Check, CheckCheck, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Circle, CircleAlert, Clock3, Copy, Download, ExternalLink, FileText, Globe2, Inbox, Layers3, LayoutDashboard, Link2, ListFilter, Menu, MoreHorizontal, Plus, Radio, Search, Send, ShieldCheck, Sparkles, Wallet, X, Zap, type LucideIcon } from 'lucide-react';
import { applyEvent, createPayment, csv, dateLabel, decimal, initials, isPayment, labels, money, needsAttention, statusOrder, sum, tokenAmount, units, type Payment, type Status, type EventKind } from '@/lib/payments';
import { samplePayments } from '@/lib/sample';

type View = 'overview' | 'payments' | 'inbox' | 'activity' | 'connections';
const navigation: { id: View; title: string; icon: LucideIcon }[] = [
  { id: 'overview', title: 'Overview', icon: LayoutDashboard }, { id: 'payments', title: 'Payments', icon: ArrowDownLeft }, { id: 'inbox', title: 'Needs attention', icon: Inbox }, { id: 'activity', title: 'Activity', icon: Radio }, { id: 'connections', title: 'Connections', icon: Layers3 },
];
const icons: Record<Status, LucideIcon> = { awaiting: Clock3, processing: Radio, completed: CheckCircle2, attention: CircleAlert, returned: ArrowDownLeft };
const STORE = 'paytrace-workspace-v1';
function Brand({ small = false }: { small?: boolean }) { return <div className={`brand ${small ? 'small' : ''}`}><span className="brand-mark"><span /><span /><span /></span><span>paytrace<span className="brand-dot">.</span></span></div>; }
function Badge({ status }: { status: Status }) { const Icon = icons[status]; return <span className={`badge ${status}`}><Icon size={12} strokeWidth={2} />{labels[status]}</span>; }
function Avatar({ name, size = '' }: { name: string; size?: string }) { const hue = Array.from(name).reduce((s, c) => s + c.charCodeAt(0), 0) % 5; return <span className={`avatar hue-${hue} ${size}`}>{initials(name)}</span>; }

function Overlay({ children, onClose, title, className = '' }: { children: ReactNode; onClose: () => void; title: string; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    ref.current?.focus();
    const key = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeRef.current();
      if (event.key !== 'Tab') return;
      const nodes = Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input, select, textarea, a[href], [tabindex="0"]') ?? []).filter(n => n.getClientRects().length);
      if (!nodes.length) { event.preventDefault(); return; }
      const first = nodes[0], last = nodes[nodes.length - 1];
      if (event.shiftKey && (document.activeElement === first || document.activeElement === ref.current)) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && (document.activeElement === last || document.activeElement === ref.current)) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener('keydown', key);
    return () => { document.body.style.overflow = oldOverflow; document.removeEventListener('keydown', key); previous?.focus(); };
  }, []);
  return <div className={`overlay ${className}`} onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog" role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1}>{children}</div></div>;
}

export function Workspace() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [ready, setReady] = useState(false);
  const [view, setView] = useState<View>('overview');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<Status | 'all'>('all');
  const [period, setPeriod] = useState('30');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [tracking, setTracking] = useState(false);
  const [menu, setMenu] = useState(false);
  const [toast, setToast] = useState('');
  const [storageWarning, setStorageWarning] = useState('');
  const [note, setNote] = useState('');
  const searchRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORE);
      if (stored) {
        const data: unknown = JSON.parse(stored);
        if (!Array.isArray(data) || !data.every(isPayment)) throw new Error('Invalid saved workspace');
        setPayments(data);
      } else setPayments(samplePayments());
    } catch { setPayments(samplePayments()); setStorageWarning('Saved data could not be read. A fresh demo is shown. Export important records before closing.'); }
    setReady(true);
    const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); searchRef.current?.focus(); } };
    document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key);
  }, []);
  useEffect(() => {
    if (!ready) return;
    try { localStorage.setItem(STORE, JSON.stringify(payments)); } catch { setStorageWarning('Browser storage is unavailable. Changes will be lost on refresh; export a CSV to keep your records.'); }
  }, [payments, ready]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 4500); return () => clearTimeout(t); }, [toast]);
  const selected = payments.find(p => p.id === selectedId);
  const attention = payments.filter(needsAttention);
  const visible = payments.filter(p => period === 'all' || Date.now() - Date.parse(p.createdAt) <= Number(period) * 86400000);
  const matches = visible.filter(p => (filter === 'all' || p.status === filter) && `${p.id} ${p.customer} ${p.description} ${p.email}`.toLowerCase().includes(query.toLowerCase()));
  const settled = visible.filter(p => p.status === 'completed');
  const inTransit = visible.filter(p => p.status === 'processing');
  const received = visible.filter(p => units(p.received) > 0n);
  const navigate = (next: View) => { setView(next); setMenu(false); setQuery(''); setFilter('all'); };
  const openPayment = (p: Payment) => { setSelectedId(p.id); setTracking(false); setNote(''); };
  function exportPayments(records = matches) {
    const blob = new Blob(['\uFEFF' + csv(records)], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `paytrace-demo-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setToast(`${records.length} demo payment records exported.`);
  }
  function simulate(kind: EventKind, receivedAmount?: string) {
    if (!selected) return;
    const titles: Record<EventKind, string> = { created: 'Request created', received: 'Transfer observed', submitted: 'Payout submitted', completed: 'Provider reported completion', returned: 'Payout returned', note: 'Operator note' };
    try {
      const next = applyEvent(selected, { id: crypto.randomUUID(), kind, at: new Date().toISOString(), title: titles[kind], detail: kind === 'returned' ? 'Simulated bank rejection. Review recipient details; no actual funds moved.' : kind === 'completed' ? 'Simulated provider completion. Recipient bank receipt is not independently confirmed.' : `Demo event only. ${receivedAmount ? receivedAmount + ' demo USDC recorded.' : 'No actual funds moved.'}` }, receivedAmount);
      setPayments(items => items.map(p => p.id === next.id ? { ...next, provider: next.provider === 'Not assigned' ? 'Bridge sandbox' : next.provider } : p)); setToast('Demo event recorded. No funds moved.');
    } catch (e) { setToast(e instanceof Error ? e.message : 'Unable to record event.'); }
  }
  function saveNote(archive = false) {
    if (!selected || !note.trim()) { setToast('Add a note describing the follow-up first.'); return; }
    const next = applyEvent(selected, { id: crypto.randomUUID(), kind: 'note', at: new Date().toISOString(), title: archive ? 'Follow-up recorded · inbox item archived' : 'Operator note', detail: note.trim().slice(0, 1000) });
    setPayments(items => items.map(p => p.id === next.id ? { ...next, archived: archive || next.archived } : p)); setNote(''); setToast(archive ? 'Archived from inbox. Payment status is unchanged.' : 'Note saved to payment history.');
  }
  const selectedTitle = navigation.find(n => n.id === view)?.title ?? 'Overview';
  return <div className="app-shell">
    <a href="#main" className="skip-link">Skip to workspace</a>
    {menu && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside className={`sidebar ${menu ? 'open' : ''}`}>
      <Brand />
      <div className="workspace-switch"><span className="workspace-symbol">S</span><div><strong>Studio workspace</strong><span>Personal workspace</span></div><span className="workspace-label">DEMO</span></div>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Main navigation">{navigation.map(({ id, title, icon: Icon }) => <button key={id} onClick={() => navigate(id)} className={`nav-item ${view === id ? 'active' : ''}`} aria-current={view === id ? 'page' : undefined}><Icon size={18} /><span>{title}</span>{id === 'inbox' && attention.length > 0 && <span className="nav-count">{attention.length}</span>}{view === id && id !== 'inbox' && <span className="nav-active-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-callout"><div className="orbit-icon"><Globe2 size={23} /></div><strong>Money moves.<br />Clarity stays.</strong><p>Your payments, connected<br />from start to finish.</p><span><span className="tiny-dot" /> Built for Monad</span></div><button className="user-profile" onClick={() => { navigate('connections'); }}><span className="user-avatar">SW</span><span><strong>Studio workspace</strong><small>Demo environment</small></span><ChevronRight size={15} /></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}><Menu size={20} /></button><span className="crumb-workspace">Workspace</span><ChevronRight size={13} /><strong>{selectedTitle}</strong></div><div className="topbar-actions"><label className="global-search"><Search size={16} /><input ref={searchRef} value={query} onChange={e => { setQuery(e.target.value); if (!['payments','overview'].includes(view)) setView('payments'); }} placeholder="Find a payment..." aria-label="Search payments" /><kbd>⌘ K</kbd></label><span className="environment"><span />Demo mode</span><button className="icon-button notification" aria-label={`View ${attention.length} payment exceptions`} onClick={() => navigate('inbox')}><Bell size={19} />{attention.length > 0 && <i />}</button><span className="user-avatar top-avatar">SW</span></div></header>
      <main id="main" tabIndex={-1}>
        <div className="demo-banner"><span><Sparkles size={14} /><strong>A little clarity, before you go live.</strong><span className="banner-extra"> You’re exploring a demo workspace. All payments are simulated.</span></span><button onClick={() => navigate('connections')}>View connections <ArrowRight size={13} /></button></div>
        {storageWarning && <div className="storage-warning" role="alert"><CircleAlert size={17} />{storageWarning}</div>}
        <div className="page-heading"><div><div className="eyebrow">YOUR PAYMENT WORKSPACE</div><h1>{view === 'overview' ? 'Every payment. In perspective.' : view === 'payments' ? 'A place for every payment.' : view === 'inbox' ? 'Let’s clear things up.' : view === 'activity' ? 'The story behind every payment.' : 'Connect the dots.'}</h1><p>{view === 'overview' ? 'A clear picture of what’s arrived, what’s moving, and what needs you.' : view === 'payments' ? 'Follow every request from the first transfer to the final payout.' : view === 'inbox' ? 'A focused inbox for payments that need a human touch.' : view === 'activity' ? 'An ordered history of transfers, payout updates, and your team’s notes.' : 'Your payment infrastructure, with the connection status made clear.'}</p></div><button className="button primary" onClick={() => setCreating(true)}><Plus size={17} />New payment</button></div>
        <div className="section-toolbar"><div className="workspace-context"><span className="live-dot" /><span>Demo workspace</span><span className="toolbar-divider" /><span>{ready ? `${payments.length} payments` : 'Loading your workspace...'}</span></div><div className="toolbar-right"><label className="select-control"><Clock3 size={14} /><select aria-label="Payment date range" value={period} onChange={e => setPeriod(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="all">All time</option></select><ChevronDown size={13} /></label><button className="button secondary small-button" onClick={() => exportPayments()} disabled={!ready}><Download size={14} /><span>Export</span></button></div></div>
        {!ready ? <div className="loading-state"><span className="loader" />Preparing your workspace...</div> : <>
        {view === 'overview' && <>
          <section className="stat-grid" aria-label="Payment summary"><Metric title="Total received" value={money(sum(received, 'received'))} icon={ArrowDownLeft} footer={`${received.length} transfers recorded`} accent="teal" /><Metric title="Completed payouts" value={money(sum(settled, 'received'))} icon={CheckCheck} footer={`${settled.length} provider-reported completions`} /><Metric title="In transit" value={money(sum(inTransit, 'received'))} icon={Send} footer={`${inTransit.length} payments on their way`} /><Metric title="Needs attention" value={String(visible.filter(needsAttention).length).padStart(2,'0')} icon={CircleAlert} footer="A little follow-up goes a long way" accent="amber" action={() => navigate('inbox')} /></section>
          <div className="insight-grid"><VolumeChart payments={visible} /><section className="card flow-card"><div className="card-heading"><div><h2>Where things stand</h2><p>Payment status, at a glance</p></div><span className="plain-icon"><Layers3 size={17} /></span></div><div className="flow-total"><strong>{visible.length}</strong><span>payments in this period</span></div><div className="status-strip" aria-label="Payment status distribution">{statusOrder.map(status => { const count = visible.filter(p => p.status === status).length; return count ? <button key={status} style={{ flex: count }} className={status} title={`${labels[status]}: ${count}`} aria-label={`${count} ${labels[status]} payments`} onClick={() => { setFilter(status); setView('payments'); }} /> : null; })}</div><div className="status-legend">{statusOrder.map(status => <button key={status} onClick={() => { setFilter(status); setView('payments'); }}><span className={`legend-dot ${status}`} /><span>{labels[status]}</span><strong>{visible.filter(p => p.status === status).length}</strong></button>)}</div><div className="card-footnote"><ShieldCheck size={14} /><span>Provider completion ≠ confirmed bank receipt.</span></div></section></div>
          {attention.length > 0 && <button className="attention-banner" onClick={() => navigate('inbox')}><span className="attention-icon"><CircleAlert size={20} /></span><span><strong>{attention.length} payments could use your attention</strong><small>Review amount mismatches and returned payouts in one place.</small></span><span className="attention-link">Open inbox <ArrowRight size={16} /></span></button>}
        </>}
        {(view === 'overview' || view === 'payments') && <section className="card payments-card"><div className="card-heading"><div><h2>{view === 'overview' ? 'Recent payments' : 'All payments'} <span className="count-pill">{matches.length}</span></h2><p>{view === 'overview' ? 'The latest movements across your workspace' : 'Find the details. Follow the money.'}</p></div>{view === 'overview' ? <button className="text-button" onClick={() => navigate('payments')}>View all payments <ArrowRight size={15} /></button> : <button className="icon-button" aria-label="Export filtered payments" onClick={() => exportPayments()}><Download size={17} /></button>}</div><div className="table-controls"><div className="filter-tabs" role="group" aria-label="Filter by status">{(['all','completed','processing','attention'] as const).map(s => <button key={s} onClick={() => setFilter(s)} aria-pressed={filter === s} className={filter === s ? 'selected' : ''}>{s === 'all' ? 'All payments' : labels[s]}{s === 'attention' && <span>{visible.filter(p => p.status === 'attention').length}</span>}</button>)}</div><label className="table-search"><Search size={15} /><input aria-label="Filter payments by name or reference" placeholder="Search by name or reference" value={query} onChange={e => setQuery(e.target.value)} /></label><label className="filter-select" title="All status filters"><ListFilter size={16} /><select aria-label="All payment statuses" value={filter} onChange={e => setFilter(e.target.value as Status | 'all')}><option value="all">All statuses</option>{statusOrder.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label></div><PaymentTable payments={view === 'overview' ? matches.slice(0, 6) : matches} onOpen={openPayment} /><div className="table-footer"><span>{matches.length ? `Showing ${view === 'overview' ? Math.min(6, matches.length) : matches.length} of ${matches.length} payments` : 'No payments match these filters'}</span><span><span className="tiny-dot" /> Sample data · stored on this device</span></div></section>}
        {view === 'inbox' && <section className="card inbox-card"><div className="card-heading"><div><h2>Open exceptions <span className="count-pill">{attention.length}</span></h2><p>Recording a follow-up never changes a payment’s financial status.</p></div><Inbox size={20} /></div>{attention.length ? attention.map(p => <button className="exception-row" key={p.id} onClick={() => openPayment(p)}><span className={`exception-symbol ${p.status}`}><CircleAlert size={21} /></span><div className="exception-copy"><div><strong>{p.status === 'attention' ? 'Received amount doesn’t match' : 'Payout returned by provider'}</strong><Badge status={p.status} /></div><p>{p.customer} <span>·</span> {p.id} <span>·</span> {p.status === 'attention' ? `${money(p.received)} received of ${money(p.amount)} requested` : 'Review recipient details and follow up with the provider.'}</p></div><ChevronRight size={19} /></button>) : <Empty icon={CheckCheck} title="You’re all caught up." text="There are no open exceptions. Payment updates that need your attention will appear here." />}</section>}
        {view === 'activity' && <section className="card activity-card"><div className="card-heading"><div><h2>Workspace activity</h2><p>Every event below is part of the demo environment.</p></div><Radio size={19} /></div>{visible.flatMap(p => p.events.map(event => ({ p, event }))).sort((a,b) => Date.parse(b.event.at) - Date.parse(a.event.at)).slice(0, 60).map(({ p, event }) => <button key={event.id} className="activity-row" onClick={() => openPayment(p)}><span className={`event-icon ${event.kind}`}><EventIcon kind={event.kind} /></span><div><strong>{event.title}</strong><span>{p.customer} · {p.id}</span></div><time dateTime={event.at}>{dateLabel(event.at)} · {new Date(event.at).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</time><ChevronRight size={15} /></button>)}{!visible.length && <Empty icon={Radio} title="No activity in this period" text="Choose a wider date range or create your first payment request." />}</section>}
        {view === 'connections' && <><div className="connection-intro"><span className="connection-illustration"><Link2 size={30} /></span><div><h2>A clear boundary between demo and live.</h2><p>This workspace is a local prototype. No wallet, bank account, or payment provider is connected. Explore the complete workflow with simulated events.</p></div></div><div className="connection-grid">{[{ title: 'Monad', subtitle: 'Blockchain transfer evidence', icon: Zap, detail: 'A separate read-only verifier checks real test USDC transfers. This demo workspace still uses simulated payment events.', mark: 'M' }, { title: 'Bridge', subtitle: 'Payout status and returns', icon: Layers3, detail: 'Demo adapter only. No Bridge credentials or webhook connection are configured.', mark: 'B' }, { title: 'Brale', subtitle: 'Stablecoin payment operations', icon: Wallet, detail: 'Demo adapter only. Provider API access and supported routes must be verified before integration.', mark: 'b' }].map(c => <section className="card connection-card" key={c.title}><div className="connection-card-top"><span className={`provider-logo ${c.title.toLowerCase()}`}>{c.mark}</span><span className="connection-status"><Circle size={10} />Not connected</span></div><h2>{c.title}</h2><strong>{c.subtitle}</strong><p>{c.detail}</p><div className="connection-card-footer"><ShieldCheck size={15} />No keys or permissions requested</div></section>)}</div><section className="card next-step-card"><div><h2>Real transaction evidence is ready to try.</h2><p>Inspect a real USDC transfer on Monad testnet. We check the network, finalized receipt, token contract, recipient and exact amount. The result stays separate from this demo workspace.</p></div><Link href="/verify" className="button primary">Verify a testnet transfer <ArrowRight size={16} /></Link></section></>}
        </>}
        <footer className="page-footer"><span><span className="brand-mini">p.</span>Every payment, accounted for.</span><span>Built on clarity. Built for <strong>Monad <span className="monad-glyph">◇</span></strong></span></footer>
      </main>
    </div>
    {toast && <div role="status" className="toast"><CheckCircle2 size={18} /><span>{toast}</span><button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={15} /></button></div>}
    {creating && <CreateDialog onClose={() => setCreating(false)} onCreate={p => { setPayments(items => [p, ...items]); setCreating(false); setView('payments'); setFilter('all'); setQuery(''); setPeriod('30'); openPayment(p); setToast('Demo request created. No email or payment was sent.'); }} />}
    {selected && <Overlay title={tracking ? 'Customer tracking preview' : `Payment ${selected.id}`} onClose={() => setSelectedId(null)} className={tracking ? 'tracking-overlay' : 'sheet-overlay'}><div className="sheet-top"><button className="text-button" onClick={() => tracking ? setTracking(false) : setSelectedId(null)}><ChevronLeft size={16} />{tracking ? 'Back to payment' : 'Payments'}</button><button className="icon-button" aria-label="Close payment details" onClick={() => setSelectedId(null)}><X size={20} /></button></div>{tracking ? <Tracking payment={selected} /> : <>
      <div className="sheet-header"><div className="detail-customer"><Avatar name={selected.customer} size="large" /><div><h2>{selected.customer}</h2><span>{selected.email}</span></div></div><div className="detail-amount">{tokenAmount(selected.amount)}<span>USDC</span></div><div className="detail-status"><Badge status={selected.status} /><span>{selected.id}</span></div><p className="detail-description">{selected.description || 'Payment request'}</p><div className="detail-actions"><button className="button secondary" onClick={() => setTracking(true)}><ExternalLink size={15} />Tracking preview</button><button className="icon-button outlined" aria-label="Copy payment reference" onClick={async () => { try { await navigator.clipboard.writeText(selected.id); setToast('Payment reference copied.'); } catch { setToast(`Reference: ${selected.id}`); } }}><Copy size={16} /></button><button className="icon-button outlined" aria-label="Export this payment" onClick={() => exportPayments([selected])}><Download size={16} /></button></div></div>
      <div className="sheet-body"><div className="detail-demo-note"><Sparkles size={15} /><span>Demo payment · all transfers and payout events are simulated.</span></div>{selected.status === 'attention' && <div className="detail-alert"><CircleAlert size={18} /><div><strong>Amount mismatch</strong><p>{tokenAmount(selected.received)} received against {tokenAmount(selected.amount)} requested. {units(selected.amount) > units(selected.received) ? `${tokenAmount(decimal(units(selected.amount) - units(selected.received)))} USDC remains unmatched.` : 'The received amount exceeds the request.'}</p></div></div>}{selected.status === 'returned' && <div className="detail-alert"><CircleAlert size={18} /><div><strong>This payout was returned</strong><p>Review recipient details and follow up with the provider. A return does not mean the customer has been refunded.</p></div></div>}
      <dl className="detail-facts"><div><dt>Requested</dt><dd>{tokenAmount(selected.amount)} USDC</dd></div><div><dt>Received</dt><dd>{tokenAmount(selected.received)} USDC</dd></div><div><dt>Payout provider</dt><dd>{selected.provider}</dd></div><div><dt>Created</dt><dd>{dateLabel(selected.createdAt)}</dd></div><div><dt>Due</dt><dd>{dateLabel(selected.dueAt)}</dd></div><div><dt>Evidence source</dt><dd>Simulation</dd></div></dl>
      <div className="detail-section-title"><h3>Payment timeline</h3><span>{selected.events.length} events</span></div><Timeline payment={selected} />
      <section className="simulation-box"><div><Sparkles size={16} /><h3>Try the payment journey</h3></div><p>Generate a clearly labelled demo event. Nothing is sent to a blockchain or bank.</p><div className="simulation-actions">{selected.status === 'awaiting' && <><button className="button secondary" onClick={() => simulate('received', selected.amount)}>Simulate matching transfer</button><button className="button secondary" onClick={() => simulate('received', decimal(units(selected.amount) / 2n || 1n))}>Simulate amount mismatch</button></>}{selected.status === 'processing' && <><button className="button secondary" onClick={() => simulate('completed')}>Simulate completion</button><button className="button secondary" onClick={() => simulate('returned')}>Simulate return</button></>}{selected.status === 'completed' && <button className="button secondary" onClick={() => simulate('returned')}>Simulate later return</button>}{['attention','returned'].includes(selected.status) && <span className="muted">This exception requires a follow-up. Record what you’ve checked below.</span>}</div></section>
      <section className="notes-section"><h3>Follow-up notes</h3><label className="sr-only" htmlFor="follow-up">Follow-up note</label><textarea id="follow-up" value={note} maxLength={1000} onChange={e => setNote(e.target.value)} placeholder="What did you check? What happens next?" /><div><button className="button secondary" disabled={!note.trim()} onClick={() => saveNote()}>Save note</button>{needsAttention(selected) && <button className="button primary" disabled={!note.trim()} onClick={() => saveNote(true)}>Save & archive from inbox</button>}</div><p>Archiving acknowledges your follow-up. It does not settle or refund the payment.</p></section></div></>}</Overlay>}
  </div>;
}

function Metric({ title, value, icon: Icon, footer, accent = '', action }: { title: string; value: string; icon: LucideIcon; footer: string; accent?: string; action?: () => void }) {
  const content = <><div className="metric-top"><span>{title}</span><span className={`metric-icon ${accent}`}><Icon size={16} /></span></div><strong className="metric-value">{value}</strong><div className="metric-footer"><span className={`metric-dot ${accent}`} />{footer}{action && <ArrowRight size={13} />}</div></>;
  return action ? <button className={`card metric ${accent} clickable`} onClick={action}>{content}</button> : <div className={`card metric ${accent}`}>{content}</div>;
}

function VolumeChart({ payments }: { payments: Payment[] }) {
  const days = Array.from({ length: 7 }, (_, i) => { const date = new Date(); date.setDate(date.getDate() - 6 + i); return date; });
  const amounts = days.map(day => payments.filter(p => p.events.some(e => e.kind === 'received' && new Date(e.at).toDateString() === day.toDateString())).reduce((s, p) => s + Number(p.received), 0));
  const max = Math.max(...amounts, 1000);
  const total = amounts.reduce((s, n) => s + n, 0);
  return <section className="card volume-card"><div className="card-heading"><div><h2>Payment flow</h2><p>Received volume over the last 7 days</p></div><span className="chart-key"><span />Demo USDC</span></div><div className="chart-total"><strong>{money(String(total))}</strong><span>recorded in this view</span></div><div className="chart-wrap"><div className="chart-labels">{[1, .75, .5, .25, 0].map(n => <span key={n}>{money(String(max * n), true)}</span>)}</div><div className="chart-plot"><div className="chart-lines">{[0,1,2,3,4].map(i => <span key={i} />)}</div><div className="chart-bars">{days.map((day, i) => <div className="chart-column" key={day.toDateString()}><div className={`bar ${i === days.length - 1 ? 'last' : ''}`} style={{ height: `${Math.max(amounts[i] / max * 100, amounts[i] ? 2 : 0)}%`, animationDelay: `${i * 45}ms` }} tabIndex={0} aria-label={`${dateLabel(day.toISOString())}: ${money(String(amounts[i]))} received`}><span className="bar-tooltip">{money(String(amounts[i]))}</span></div><span className="bar-label">{day.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div>)}</div></div></div></section>;
}

function PaymentTable({ payments, onOpen }: { payments: Payment[]; onOpen: (p: Payment) => void }) {
  if (!payments.length) return <Empty icon={Search} title="No payments found" text="Try another name, reference, date range, or status filter." />;
  return <div className="table-scroll"><table><thead><tr><th>Customer / reference</th><th>Amount</th><th>Status</th><th className="provider-column">Provider</th><th className="date-column">Created <ArrowDown size={11} /></th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{payments.map(p => <tr key={p.id}><td><button className="customer-cell" onClick={() => onOpen(p)}><Avatar name={p.customer} /><span><strong>{p.customer}</strong><small>{p.id} <span>·</span> {p.description}</small></span></button></td><td><strong className="table-amount">{money(p.amount)}</strong><small className="currency-label">USDC</small></td><td><Badge status={p.status} /></td><td className="provider-column"><span className="provider-cell">{p.provider === 'Not assigned' ? <span className="muted">—</span> : <><span className={`provider-mini ${p.provider.startsWith('Bridge') ? '' : 'brale'}`}>{p.provider.startsWith('Bridge') ? 'B' : 'b'}</span>{p.provider.replace(' sandbox','')}<small>Demo</small></>}</span></td><td className="date-column">{dateLabel(p.createdAt)}</td><td><button className="row-open icon-button" aria-label={`Open payment ${p.id} for ${p.customer}`} onClick={() => onOpen(p)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table></div>;
}
function Empty({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <div className="empty-state"><span><Icon size={25} /></span><h3>{title}</h3><p>{text}</p></div>; }
function EventIcon({ kind }: { kind: EventKind }) { const Icon = kind === 'completed' ? Check : kind === 'returned' ? CircleAlert : kind === 'received' ? ArrowDownLeft : kind === 'submitted' ? Send : FileText; return <Icon size={15} />; }
function Timeline({ payment, customerView = false }: { payment: Payment; customerView?: boolean }) { return <ol className="timeline">{payment.events.filter(e => !customerView || e.kind !== 'note').map(e => <li key={e.id}><span className={`event-icon ${e.kind}`}><EventIcon kind={e.kind} /></span><div><strong>{e.title}</strong><p>{e.detail}</p><time dateTime={e.at}>{dateLabel(e.at)} · {new Date(e.at).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</time></div></li>)}</ol>; }
function Tracking({ payment }: { payment: Payment }) { return <div className="tracking-content"><Brand small /><span className="preview-label">LOCAL PREVIEW · SIMULATED PAYMENT</span><div className={`tracking-symbol ${payment.status}`}><Wallet size={29} /></div><h2>{payment.status === 'completed' ? 'Your payout has an update.' : payment.status === 'returned' ? 'Your payout needs a follow-up.' : payment.status === 'attention' ? 'We’re checking your payment.' : payment.status === 'awaiting' ? 'Your payment request is ready.' : 'Your payment is on its way.'}</h2><p>{payment.description || 'Payment request'} · {payment.id}</p><strong className="tracking-amount">{tokenAmount(payment.amount)} <span>USDC</span></strong><Badge status={payment.status} /><div className="tracking-summary"><div><span>Requested</span><strong>{tokenAmount(payment.amount)}</strong></div><div><span>Received</span><strong>{tokenAmount(payment.received)}</strong></div></div><Timeline payment={payment} customerView /><div className="tracking-disclaimer"><ShieldCheck size={17} /><p>This is a preview stored on this device, not a shareable public payment link. All events are simulated. Provider completion does not independently confirm receipt in a bank account.</p></div></div>; }

function CreateDialog({ onClose, onCreate }: { onClose: () => void; onCreate: (p: Payment) => void }) {
  const [error, setError] = useState('');
  return <Overlay title="Create payment request" onClose={onClose} className="create-overlay"><div className="dialog-header"><div><span className="eyebrow">BRING A PAYMENT INTO FOCUS</span><h2>New payment request</h2></div><button className="icon-button" onClick={onClose} aria-label="Close new payment form"><X size={20} /></button></div><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); try { onCreate(createPayment({ customer: String(data.get('customer')), email: String(data.get('email')), amount: String(data.get('amount')), description: String(data.get('description')), country: String(data.get('country')) })); } catch (err) { setError(err instanceof Error ? err.message : 'Please check the payment details.'); } }}><div className="form-note"><Sparkles size={16} /><span>Create a demo request. No email is sent and no money moves.</span></div><label>Customer or business name<input name="customer" required maxLength={80} placeholder="e.g. Orbit Studio" autoComplete="organization" /></label><label>Email address<input name="email" type="email" required maxLength={254} placeholder="hello@example.com" autoComplete="email" /></label><div className="form-grid"><label>Amount<div className="amount-input"><span>$</span><input name="amount" required inputMode="decimal" placeholder="0.00" pattern="[0-9]{1,12}(\.[0-9]{1,6})?" /><span>USDC</span></div></label><label>Customer region<select name="country" defaultValue="NG"><option value="NG">Nigeria</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="EU">Europe</option><option value="OTHER">Other</option></select></label></div><label>What is this payment for?<textarea name="description" maxLength={240} placeholder="e.g. October design retainer" rows={3} /></label><p className="form-hint"><Clock3 size={14} />Due in 7 days · Demo USDC · Payout provider not assigned</p>{error && <div className="form-error" role="alert">{error}</div>}<div className="dialog-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit">Create request <ArrowRight size={16} /></button></div></form></Overlay>;
}
